Console rework started

diff --git a/worlds/haxima-1.001/tests/testexec b/worlds/haxima-1.001/tests/testexec
--- a/worlds/haxima-1.001/tests/testexec
+++ b/worlds/haxima-1.001/tests/testexec
@@ -29,5 +29,12 @@ test=$1
     exit -3
   fi
 
+  diff $test.console $test.console.mstr > $test.console.diff
+  if [ $? != 0 ]; then
+    printf "FAIL [diff console]\n"
+    exit -3
+  fi
+
   printf " PASS\n"
 
+exit 0
